name: deploy blog to aliyun
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:10
      - name: use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      # build
      - name: build
        run: |
          yarn && yarn build
        env:
          CI: true
      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: ".vitepress/dist/"
          REMOTE_HOST: "outlove.cn"
          REMOTE_USER: "root"
          TARGET: "/root/home/www/pi/"
